fixtures:
  repositories:
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.1.0'
    apt:
      repo: 'git://github.com/puppetlabs/puppetlabs-apt.git'
      ref: '1.8.0'
    augeasproviders_pam:
      repo: 'git://github.com/hercules-team/augeasproviders_pam.git'
      ref: '2.0.3'
    augeasproviders_core:
      repo: 'git://github.com/hercules-team/augeasproviders_core.git'
      ref: '2.1.1'
    epel:
      repo: 'git://github.com/stahnma/puppet-module-epel.git'
      ref: '1.0.0'
  symlinks:
    yubikey: "#{source_dir}"
