HOSTS:
  centos-agent.localdomain:
    roles:
    - "agent"
    type: aio
    platform: "el-7-x86_64"
    docker_cmd: '["/sbin/init"]'
    image: "centos:7"
    hypervisor: "docker"
    docker_preserve_image: true
CONFIG:
  masterless: true
